#!/usr/bin/env bash
# check_boundaries.sh — mechanical checks for a Go modular monolith (see modular-monolith-boundaries SKILL.md).
# Run from the repo root of any Go modular monolith. Configure via env: MODULE_PATH, DOMAIN_MODULES, BASE_REF. Exit code 0 = all checks passed.
#
# These duplicate what depguard/CI should already enforce. That's deliberate: this script runs in the
# reviewer's context even when CI hasn't, and a reviewer that trusts CI blindly is a reviewer that
# missed the PR which edited .golangci.yml.

set -uo pipefail

MODULE_PATH="${MODULE_PATH:-$(go list -m 2>/dev/null || sed -n 's/^module //p' go.mod)}"
DOMAIN_MODULES="${DOMAIN_MODULES:-customer billing wiki chat}"
BASE_REF="${BASE_REF:-origin/main}"
fail=0

red()   { printf '\033[31mFAIL\033[0m %s\n' "$*"; fail=1; }
ok()    { printf '\033[32m ok \033[0m %s\n' "$*"; }
skip()  { printf '\033[33mskip\033[0m %s\n' "$*"; }

if [ -z "$MODULE_PATH" ]; then
  echo "cannot determine Go module path (no go.mod?) — run from platform-api root" >&2
  exit 2
fi

# Imports of a package, restricted to this repo, excluding the package itself.
repo_imports() {
  go list -f '{{join .Imports "\n"}}' "./$1/..." 2>/dev/null | grep "^${MODULE_PATH}/" | sed "s#^${MODULE_PATH}/##" | sort -u
}

# ---- 1. Domain modules import only core and their own subpackages ----------------------------
for m in $DOMAIN_MODULES; do
  [ -d "$m" ] || { skip "$m/ not present yet"; continue; }
  bad=$(repo_imports "$m" | grep -v "^core\(/\|$\)" | grep -v "^${m}\(/\|$\)" || true)
  if [ -n "$bad" ]; then
    red "boundary: $m imports forbidden repo packages:"; echo "$bad" | sed 's/^/       /'
  else
    ok "$m imports only core and itself"
  fi
done

# ---- 2. core imports nothing else in the repo ---------------------------------------------------
if [ -d core ]; then
  bad=$(repo_imports core | grep -v "^core\(/\|$\)" || true)
  [ -n "$bad" ] && { red "dependency direction: core imports repo packages:"; echo "$bad" | sed 's/^/       /'; } || ok "core imports nothing else in the repo"
fi

# ---- 3. auth imports only core ------------------------------------------------------------------
if [ -d auth ]; then
  bad=$(repo_imports auth | grep -v "^core\(/\|$\)" | grep -v "^auth\(/\|$\)" || true)
  [ -n "$bad" ] && { red "dependency direction: auth imports beyond core:"; echo "$bad" | sed 's/^/       /'; } || ok "auth imports only core"
fi

# ---- 4. Only cmd/server/wiring imports more than one domain module ------------------------------
for pkg in $(go list ./... 2>/dev/null | sed "s#^${MODULE_PATH}/##" | grep -v '^cmd/server/wiring'); do
  imps=$(go list -f '{{join .Imports "\n"}}' "./$pkg" 2>/dev/null | grep "^${MODULE_PATH}/" | sed "s#^${MODULE_PATH}/##" | awk -F/ '{print $1}' | sort -u)
  count=0
  for m in $DOMAIN_MODULES; do echo "$imps" | grep -qx "$m" && count=$((count+1)); done
  # cmd/server/main.go legitimately imports all modules to mount them; that's allowed. Everything else is not.
  if [ "$count" -gt 1 ] && [ "$pkg" != "cmd/server" ]; then
    red "wiring: $pkg imports $count domain modules (only cmd/server and cmd/server/wiring may)"
  fi
done
ok "multi-module imports confined to cmd/server{,/wiring} (or none found)"

# ---- 5. Storage code lives under internal/ ------------------------------------------------------
for m in $DOMAIN_MODULES; do
  [ -d "$m" ] || continue
  for d in migrations queries db; do
    found=$(find "$m" -type d -name "$d" -not -path "*/internal/*" 2>/dev/null)
    [ -n "$found" ] && red "storage placement: $found is storage code outside $m/internal/"
  done
  # sqlc-generated files carry a header; make sure none escaped internal/
  found=$(grep -rl --include='*.go' '^// Code generated by sqlc' "$m" 2>/dev/null | grep -v "/internal/" || true)
  [ -n "$found" ] && { red "storage placement: sqlc output outside internal/:"; echo "$found" | sed 's/^/       /'; }
done
ok "storage code placement checked"

# ---- 6. No SQL references another module's schema ----------------------------------------------
for m in $DOMAIN_MODULES; do
  [ -d "$m" ] || continue
  for other in $DOMAIN_MODULES; do
    [ "$m" = "$other" ] && continue
    hits=$(grep -rn --include='*.sql' -E "\b${other}\.[a-z_]+" "$m" 2>/dev/null || true)
    [ -n "$hits" ] && { red "cross-schema SQL: $m SQL references schema '$other':"; echo "$hits" | sed 's/^/       /'; }
  done
done
ok "cross-schema SQL references checked"

# ---- 7. Tenant-owned tables have RLS in the same migration ----------------------------------------
for f in $(find . -path '*/internal/migrations/*.sql' 2>/dev/null); do
  if grep -qiE 'create table' "$f" && grep -qi 'tenant_id' "$f"; then
    grep -qiE 'enable row level security' "$f" || red "tenant isolation: $f creates a tenant_id table without ENABLE ROW LEVEL SECURITY"
    grep -qiE 'create policy' "$f"            || red "tenant isolation: $f creates a tenant_id table without CREATE POLICY"
  fi
done
ok "RLS presence in migrations checked"

# ---- 8. No new go.mod requires relative to base -------------------------------------------------
if git rev-parse --verify -q "$BASE_REF" >/dev/null; then
  added=$(git diff "$BASE_REF" -- go.mod | grep '^+' | grep -vE '^\+\+\+|^\+module|^\+go |^\+toolchain' | grep -E '^\+\s*[a-z0-9.\-/]+ v' || true)
  [ -n "$added" ] && { red "dependencies: go.mod adds requires (needs ADR):"; echo "$added" | sed 's/^/       /'; } || ok "no new go.mod requires vs $BASE_REF"
else
  skip "$BASE_REF not available; go.mod diff not checked"
fi

# ---- 9. sqlc output is current ------------------------------------------------------------------
if command -v sqlc >/dev/null 2>&1 && [ -f sqlc.yaml ] || [ -f sqlc.yml ] || [ -f sqlc.json ]; then
  if sqlc generate >/dev/null 2>&1; then
    if git diff --quiet -- '*/internal/db/*' 2>/dev/null; then ok "sqlc output is current"; else red "codegen: sqlc generate produced changes — regenerate and commit"; fi
  else
    red "codegen: sqlc generate failed (query/schema mismatch)"
  fi
else
  skip "sqlc not available or not configured; generation check skipped"
fi

echo
if [ "$fail" -eq 0 ]; then echo "ALL CHECKS PASSED"; else echo "CHECKS FAILED — see FAIL lines above"; fi
exit $fail
