set-option -g base-index 0
set-option -g mouse on
set-option -g renumber-windows on

# Update the status bar every 5 seconds with system info
set -g status-interval 5
set -g status-right-length 100
set -g status-right "#[bg=colour238,fg=white] #(~/.config/tmux/tmux_status.sh) "
